
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - CNAME

#Ensure capatibility with Github Pages
safe: true

collections:
  - cards

#Misc Settings
google_analytics_id: UA-484023-11
baseurl=/david